name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres_test:
        image: postgres
        ports:
          - 5433:5432
        env:
          - POSTGRES_USER: test
          - POSTGRES_PASSWORD: password
          - POSTGRES_DB: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt
        run: cd backebd

      - name: Test Authorization
        run: pytest auth_tests.py
      - name: Test Database
        run: pytest database_tests.py