name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt
      - name: Tests
        run: pytest backend\authorization\auth_tests.py
  revert-change:
    runs-on: ubuntu-latest
    needs: [ tests ]
    if: ${{ needs.tests.result == 'failure' }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Revert the commit that triggered this run, then push ot to main
        shell: bash
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name "RomanovYehor"
          git config user.email "yeghor.romanov@gmail.com"
          git revert --no-edit ${{ github.sha }}
          git push origin main